language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5"
  - "3.6"
  - "3.7

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "nightly"

install:
    - pip install -r requirements.txt

script: python -B test/test.py
